#!/usr/bin/env python3
from pathlib import Path
p=Path('src/core/sim.cpp');s=p.read_text()
anchor='''inline float roundWorldVy(float worldVy, bool flip) {\n  double rel = static_cast<double>(worldVy) * (flip ? -1.0 : 1.0) * phys::TPS;\n  const double sign = flip ? 1.0 : -1.0;\n  double n = rel / 54.0 * sign;\n  const double truncated = static_cast<int>(n);\n  if (n != truncated) n = std::round((n - truncated) * 1000.0) / 1000.0 + truncated;\n  rel = n * 54.0 * sign;\n  return static_cast<float>(rel * (flip ? -1.0 : 1.0) / phys::TPS);\n}\n'''
helper=anchor+'''\ninline float cubePadUS(PadKind k, bool mini) {\n  float v = 0.0f;\n  switch (k) {\n    case PadKind::Yellow: v = 864.0f; break;\n    case PadKind::Pink: v = 561.6f; break;\n    case PadKind::Red: v = 1080.0f; break;\n    case PadKind::Blue: v = -345.6f; break;\n  }\n  return mini ? v * 0.8f : v;\n}\n\ninline float cubeOrbUS(OrbKind k, int tier, bool mini) {\n  const int i = std::clamp(tier, 0, 3);\n  static constexpr float yellow[4] = {573.48f,603.72f,616.68f,606.42f};\n  static constexpr float blue[4]   = {-229.392f,-241.488f,-246.672f,-242.568f};\n  static constexpr float pink[4]   = {412.884f,434.7f,443.988f,436.644f};\n  static constexpr float red[4]    = {779.976f,821.448f,839.43f,825.174f};\n  static constexpr float green[4]  = {562.032f,592.056f,605.07f,594.756f};\n  float v = 0.0f;\n  switch (k) {\n    case OrbKind::Yellow: v=yellow[i]; break;\n    case OrbKind::Blue: v=blue[i]; break;\n    case OrbKind::Pink: v=pink[i]; break;\n    case OrbKind::Red: v=red[i]; break;\n    case OrbKind::Green: v=green[i]; break;\n    case OrbKind::Black: v=-810.0f; break;\n    case OrbKind::Dash: v=0.0f; break;\n  }\n  if (!mini) return v;\n  if (k == OrbKind::Yellow) { static constexpr float a[4]={458.784f,482.976f,481.734f,485.136f}; return a[i]; }\n  if (k == OrbKind::Blue)   { static constexpr float a[4]={-183.519f,-193.185f,-197.343f,-194.049f}; return a[i]; }\n  if (k == OrbKind::Pink)   { static constexpr float a[4]={330.318f,347.76f,355.212f,349.272f}; return a[i]; }\n  if (k == OrbKind::Red)    { static constexpr float a[4]={621.702f,654.858f,669.222f,657.828f}; return a[i]; }\n  if (k == OrbKind::Green)  { static constexpr float a[4]={447.336f,471.312f,481.734f,485.136f}; return a[i]; }\n  return v;\n}\n'''
if anchor not in s: raise SystemExit('round helper anchor')
s=s.replace(anchor,helper,1)
old='''void Sim::applyPad(const Object& o) {\n  lastContactUid_ = o.uid;\n  st_.lastPadUid = o.uid;\n  switch (static_cast<PadKind>(o.sub)) {\n    case PadKind::Yellow: boost(phys::PAD_YELLOW); break;\n    case PadKind::Pink: boost(phys::PAD_PINK); break;\n    case PadKind::Red: boost(phys::PAD_RED); break;\n    case PadKind::Blue:\n      st_.flip = !st_.flip;\n      boost(phys::PAD_BLUE, /*alongGravity=*/true);\n      break;\n  }\n}\n'''
new='''void Sim::applyPad(const Object& o) {\n  lastContactUid_ = o.uid;\n  st_.lastPadUid = o.uid;\n  const PadKind k = static_cast<PadKind>(o.sub);\n  if (st_.mode == Mode::Cube) {\n    if (k == PadKind::Blue) st_.flip = !st_.flip;\n    const float rel = cubePadUS(k, st_.mini);\n    st_.vy = (rel / phys::TPS) * st_.gdir();\n    st_.onGround = false;\n    return;\n  }\n  switch (k) {\n    case PadKind::Yellow: boost(phys::PAD_YELLOW); break;\n    case PadKind::Pink: boost(phys::PAD_PINK); break;\n    case PadKind::Red: boost(phys::PAD_RED); break;\n    case PadKind::Blue: st_.flip=!st_.flip; boost(phys::PAD_BLUE,true); break;\n  }\n}\n'''
if old not in s: raise SystemExit('applyPad anchor')
s=s.replace(old,new,1)
old='''void Sim::applyOrb(const Object& o) {\n  lastContactUid_ = o.uid;\n  st_.lastOrbUid = o.uid;\n  switch (static_cast<OrbKind>(o.sub)) {\n    case OrbKind::Yellow: boost(phys::ORB_YELLOW); break;\n    case OrbKind::Pink: boost(phys::ORB_PINK); break;\n    case OrbKind::Red: boost(phys::ORB_RED); break;\n    case OrbKind::Blue:\n      st_.flip = !st_.flip;\n      boost(phys::ORB_BLUE, /*alongGravity=*/true);\n      break;\n    case OrbKind::Green:\n      st_.flip = !st_.flip;\n      boost(phys::ORB_GREEN);\n      break;\n    case OrbKind::Black: boost(phys::ORB_BLACK, /*alongGravity=*/true); break;\n    case OrbKind::Dash: boost(0.0f); break;\n  }\n}\n'''
new='''void Sim::applyOrb(const Object& o) {\n  lastContactUid_ = o.uid;\n  st_.lastOrbUid = o.uid;\n  const OrbKind k = static_cast<OrbKind>(o.sub);\n  if (st_.mode == Mode::Cube) {\n    if (k == OrbKind::Blue || k == OrbKind::Green) st_.flip = !st_.flip;\n    const float rel = cubeOrbUS(k, st_.tier, st_.mini);\n    st_.vy = (rel / phys::TPS) * st_.gdir();\n    st_.onGround = false;\n    return;\n  }\n  switch (k) {\n    case OrbKind::Yellow: boost(phys::ORB_YELLOW); break;\n    case OrbKind::Pink: boost(phys::ORB_PINK); break;\n    case OrbKind::Red: boost(phys::ORB_RED); break;\n    case OrbKind::Blue: st_.flip=!st_.flip; boost(phys::ORB_BLUE,true); break;\n    case OrbKind::Green: st_.flip=!st_.flip; boost(phys::ORB_GREEN); break;\n    case OrbKind::Black: boost(phys::ORB_BLACK,true); break;\n    case OrbKind::Dash: boost(0.0f); break;\n  }\n}\n'''
if old not in s: raise SystemExit('applyOrb anchor')
p.write_text(s.replace(old,new,1))
print('exact cube effects applied')
